dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.5.3/bazel_0.5.3-linux-x86_64.deb
  - sudo dpkg -i bazel_0.5.3-linux-x86_64.deb
install:
  - pushd . && git clone http://git.veripool.org/git/verilator && cd verilator* && autoconf && ./configure && make && sudo make install && popd
script:
  - cd core/dv && make -f core.mk && bazel test :instruction_tests

